In [1]:
import numpy as np
import torch #importing otech

In [2]:
x = torch.rand(3,2)     #random input using torch
x

tensor([[0.2165, 0.6070],
        [0.8275, 0.3153],
        [0.1003, 0.9745]])

In [3]:
y = torch.ones(x.size()) #generating y using the shape of x
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [14]:
z= x +y # we can add tensor like array
z

tensor([[1.2165, 1.6070],
        [1.8275, 1.3153],
        [1.1003, 1.9745]])

In [15]:
z[0]   #same as done with array 

tensor([1.2165, 1.6070])

In [16]:
z[:,1:]  #we can also slice tensors

tensor([[1.6070],
        [1.3153],
        [1.9745]])

In [17]:
z.add(1)     #adding 1 to matric

tensor([[2.2165, 2.6070],
        [2.8275, 2.3153],
        [2.1003, 2.9745]])

In [18]:
z     #no effect ong real matric

tensor([[1.2165, 1.6070],
        [1.8275, 1.3153],
        [1.1003, 1.9745]])

In [19]:
z.add_(1)  #but using under score with add we will get inplace value

tensor([[2.2165, 2.6070],
        [2.8275, 2.3153],
        [2.1003, 2.9745]])

In [21]:
z.size()   # checking size of tensor

torch.Size([3, 2])

In [22]:
z.resize_(3,4)   #we can resixe tensor like array

tensor([[2.2165, 2.6070, 2.8275, 2.3153],
        [2.1003, 2.9745, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

# Converting numpy to tensor and creating tensor from numpy

In [24]:
a = np.random.rand(4,3)
a

array([[0.16914403, 0.02548688, 0.05276756],
       [0.08214142, 0.4322195 , 0.68792051],
       [0.85470348, 0.7430299 , 0.70721131],
       [0.34203568, 0.60378818, 0.99779933]])

In [32]:
b = torch.from_numpy(a) #converting tensor from numpy array
b

tensor([[0.3383, 0.0510, 0.1055],
        [0.1643, 0.8644, 1.3758],
        [1.7094, 1.4861, 1.4144],
        [0.6841, 1.2076, 1.9956]], dtype=torch.float64)

In [33]:
b.numpy()  #converting tensor to numpy array but memory shared by numpy and tensor is same

array([[0.33828805, 0.05097376, 0.10553513],
       [0.16428285, 0.86443899, 1.37584102],
       [1.70940696, 1.48605981, 1.41442263],
       [0.68407136, 1.20757636, 1.99559866]])

In [34]:
b.mul_(2) #multiply b with 2

tensor([[0.6766, 0.1019, 0.2111],
        [0.3286, 1.7289, 2.7517],
        [3.4188, 2.9721, 2.8288],
        [1.3681, 2.4152, 3.9912]], dtype=torch.float64)